# fly.toml app configuration file generated for ca-withered-wind on 2025-04-23T13:06:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ca-withered-wind'
primary_region = 'gru'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  processes = ['worker']

[processes]
  app = "node dist/index.js"
  worker = "node dist/worker-mirror.js"